import {useRouter} from "next/router";
import Layout from "../../components/layout";
import Container from "../../components/container";

const postsPerPage = 10;

import React from 'react';

const pages = [
    { slug: 'slug',
        title: 'title 1',
        date: '2020-03-1T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 2',
        date: '2020-03-2T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 3',
        date: '2020-03-3T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 4',
        date: '2020-03-4T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 5',
        date: '2020-03-5T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 6',
        date: '2020-03-6T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 7',
        date: '2020-03-7T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 8',
        date: '2020-03-8T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 9',
        date: '2020-03-9T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 10',
        date: '2020-03-10T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 11',
        date: '2020-03-11T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 12',
        date: '2020-03-12T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 13',
        date: '2020-03-13T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 14',
        date: '2020-03-14T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 15',
        date: '2020-03-15T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 16',
        date: '2020-03-16T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 17',
        date: '2020-03-17T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 18',
        date: '2020-03-18T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 19',
        date: '2020-03-19T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' },
    { slug: 'slug',
        title: 'title 20',
        date: '2020-03-20T05:35:07.322Z',
        coverImage: 'coverImage',
        author: { name: 'author', picture: 'author' },
        excerpt: 'excerpt',
        ogImage: { url: 'ogImage' },
        content: 'Content' }
]

const PageList = () => {
        <div>
            <ul>
                <li></li>
            </ul>
        </div>
};

export default PageList;

